"""Render a bright, detailed Ontario wildfire Sentinel map."""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
INPUT = ROOT / "outputs" / "wildfire" / "sentinel" / "ontario_sentinel_intelligence.json"
OUTPUT = ROOT / "materials" / "sentinel_ontario_wildfire.html"
WATER = "https://ws.lioservices.lrc.gov.on.ca/arcgis2/rest/services/LIO_OPEN_DATA/LIO_Open01/MapServer/25"

data = json.loads(INPUT.read_text())
fires = [{"id": fire["fire_id"], "lat": fire["lat"], "lon": fire["lon"], "score": fire["warn_score"], "tier": fire["warn_tier"], "size": fire["size_hectares"], "condition": fire["condition"], "station": fire.get("nearest_station", {})} for fire in data["fires"]]
OUTPUT.write_text(f'''<!doctype html><html><head><meta charset="utf-8"><title>Sentinel | Ontario Wildfire</title><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>body{{margin:0;background:#edf5fb;color:#102a43;font:14px system-ui}}header{{padding:18px 28px;background:#fff;border-bottom:4px solid #f97316;display:flex;justify-content:space-between}}h1{{margin:0;font-size:22px}}#map{{height:calc(100vh - 84px)}}.panel{{position:absolute;z-index:900;top:105px;right:20px;width:285px;background:#fff;border-radius:12px;padding:16px;box-shadow:0 8px 24px #173b5b44}}.pill{{display:inline-block;padding:4px 7px;background:#fff1e6;color:#a13d00;font-weight:800;border-radius:4px}}.note{{font-size:12px;color:#486581;line-height:1.4}}.legend i{{display:inline-block;width:12px;height:12px;border-radius:50%;margin-right:6px}}</style></head><body><header><div><h1>SENTINEL — Ontario Wildfire Intelligence</h1><div>Live decision support · official Ontario AFFES active-fire and weather evidence</div></div><div class="pill">EXPERIMENTAL · HUMAN APPROVAL REQUIRED</div></header><div id="map"></div><aside class="panel"><b>Operational map</b><p><b>{len(fires)}</b> active fires scored<br><b>{data['fire_weather']['fwi']['score']:.3f}</b> peak intelligence score<br><b>{data['infrastructure']['status']}</b> infrastructure status</p><div class="legend"><i style="background:#dc2626"></i>Emergency response<br><i style="background:#f97316"></i>Mitigation required<br><i style="background:#facc15"></i>Monitor<br><i style="background:#0ea5e9"></i>Ontario lakes and rivers</div><p class="note">Water is Ontario Hydro Network context. It is not a water-supply, evacuation-route, or fire-suppression availability claim. Verify all official sources before action.</p></aside><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script src="https://unpkg.com/esri-leaflet@3.0.15/dist/esri-leaflet.js"></script><script>const fires={json.dumps(fires)};const map=L.map('map').setView([50.5,-86.5],5);L.tileLayer('https://{{s}}.tile.openstreetmap.org/{{z}}/{{x}}/{{y}}.png',{{maxZoom:18,attribution:'© OpenStreetMap contributors'}}).addTo(map);L.esri.featureLayer({{url:'{WATER}',where:"WATERBODY_TYPE IN ('Lake','River')",style:()=>({{color:'#0284c7',weight:1,fillColor:'#38bdf8',fillOpacity:.42}})}}).addTo(map);const c={{EMERGENCY_RESPONSE:'#dc2626',MITIGATION_REQUIRED:'#f97316',MONITOR:'#eab308',NORMAL_OPERATION:'#22c55e'}};fires.forEach(f=>L.circleMarker([f.lat,f.lon],{{radius:7+f.score*7,color:'#fff',weight:2,fillColor:c[f.tier],fillOpacity:.95}}).bindPopup(`<b>${{f.id}}</b><br>${{f.condition}} · ${{f.size}} ha<br>Score: ${{f.score}} (${{f.tier}})<br>Nearest station FWI: ${{f.station?.fwi ?? 'unavailable'}}`).addTo(map));</script></body></html>''')
print(f"Written: {{OUTPUT}}")
